# Feature Specifications - Void Hunter: Redux
# Gherkin-Style Acceptance Tests
# Generated by: Tech Lead (Stage 3)
# Source: /artifacts/02_pm_prd.md

@epic-1-core-gameplay
Feature: Player Movement and Control
  As a player
  I want to control my spacecraft smoothly
  So that I can navigate through the asteroid field

  Background:
    Given the game is in "playing" state
    And the player spacecraft is initialized at center screen

  @desktop @movement
  Scenario: Desktop keyboard movement with WASD keys
    Given the player is using a desktop browser
    When the player presses the "W" key
    Then the player's Y velocity should increase by -5 pixels/frame
    And the spacecraft should exhibit inertia decay of 0.95 per frame
    And the spacecraft should rotate to face the movement direction

  @desktop @movement
  Scenario: Desktop keyboard movement with Arrow keys
    Given the player is using a desktop browser
    When the player presses the "Up Arrow" key
    Then the player's Y velocity should increase by -5 pixels/frame
    And the behavior should match WASD controls exactly

  @mobile @movement
  Scenario: Mobile virtual joystick control
    Given the player is using a mobile device
    And the virtual joystick is rendered in the bottom-left corner
    When the player touches the joystick at 45 degrees
    Then the spacecraft should move diagonally at normalized velocity
    And the joystick knob should visually follow the touch position
    And the movement should exhibit the same 0.95 inertia decay

  @movement @screen-wrapping
  Scenario: Spacecraft wraps around screen edges
    Given the player spacecraft is at position (10, 300)
    When the player moves left beyond X = 0
    Then the spacecraft should reappear at X = canvas.width
    And the velocity vector should be preserved

  @movement @screen-wrapping
  Scenario: Toroidal topology applies to all edges
    Given the player spacecraft is at any edge position
    When the player exits through top, bottom, left, or right edge
    Then the spacecraft should wrap to the opposite edge seamlessly

---

@epic-1-core-gameplay
Feature: Shooting Mechanics
  As a player
  I want to shoot projectiles at asteroids
  So that I can destroy them and survive

  Background:
    Given the game is in "playing" state
    And the player has a weapon equipped

  @desktop @shooting
  Scenario: Desktop mouse-aimed shooting
    Given the player is using a desktop browser
    And the mouse is at position (500, 300)
    When the player clicks the left mouse button
    Then a bullet should spawn at the player's position
    And the bullet's velocity should aim toward (500, 300)
    And a shooting sound should play (200Hz oscillator, 50ms decay)
    And a muzzle flash effect should render for 3 frames

  @desktop @shooting
  Scenario: Desktop auto-fire on hold
    Given the player is using a desktop browser
    When the player holds the left mouse button for 1 second
    Then 10 bullets should have been fired (10 bullets/second)
    And each bullet should aim at the current mouse position

  @mobile @shooting
  Scenario: Mobile fire button shooting
    Given the player is using a mobile device
    And the fire button is rendered in the bottom-right corner
    When the player taps the fire button
    Then a bullet should spawn at the player's position
    And the bullet should travel in the current aiming direction
    And the fire button should visually indicate "pressed" state (solid red)

  @shooting @bullet-lifecycle
  Scenario: Bullet despawns after maximum distance
    Given a bullet has been fired
    When the bullet travels 800 pixels without hitting anything
    Then the bullet should be removed from the game state
    And no explosion particles should spawn

  @shooting @bullet-lifecycle
  Scenario: Bullet despawns on asteroid hit
    Given a bullet is traveling toward an asteroid
    When the bullet intersects the asteroid's collision radius
    Then the bullet should be removed from the game state
    And the asteroid should take damage or split
    And an explosion sound should play

---

@epic-1-core-gameplay
Feature: Asteroid Behavior and Splitting
  As a player
  I want asteroids to split realistically
  So that destroying them feels satisfying and strategic

  Background:
    Given the game is in "playing" state

  @asteroids @splitting
  Scenario: Large asteroid splits into two medium asteroids
    Given a large asteroid exists with radius 50
    When the asteroid is destroyed by a bullet
    Then 2 medium asteroids should spawn at the destruction point
    And each medium asteroid should have radius 25
    And the medium asteroids should inherit 50% of parent velocity
    And the medium asteroids should diverge at 120-degree angles
    And 20-30 explosion particles should spawn

  @asteroids @splitting
  Scenario: Medium asteroid splits into two small asteroids
    Given a medium asteroid exists with radius 25
    When the asteroid is destroyed by a bullet
    Then 2 small asteroids should spawn at the destruction point
    And each small asteroid should have radius 12
    And the velocity inheritance rules should apply
    And the rotation speed should increase by 1.5x from parent

  @asteroids @splitting
  Scenario: Small asteroid is destroyed completely
    Given a small asteroid exists with radius 12
    When the asteroid is destroyed by a bullet
    Then no child asteroids should spawn
    And 15-20 explosion particles should spawn
    And the player's score should increase by 100 points
    And a voice line "Oh, yes!" should play (if not muted)

  @asteroids @rotation
  Scenario: Asteroid rotation speed scales with level
    Given the game is at level 3
    And a large asteroid spawns
    When the game loop updates
    Then the asteroid's rotation speed should be base_speed * (1 + 0.1 * level)
    And the rotation should be visually smooth at 60fps

  @asteroids @spawning
  Scenario: Asteroids do not spawn on top of player
    Given a new wave is starting
    When large asteroids are being spawned
    Then each asteroid's spawn position must satisfy distance(asteroid, player) > 200px
    And the spawn position should be within canvas bounds

---

@epic-1-core-gameplay
Feature: Collision Detection and Damage
  As a player
  I expect to take damage when colliding with asteroids
  So that the game has meaningful risk

  Background:
    Given the game is in "playing" state
    And the player has 100 health

  @collision @damage
  Scenario: Player collides with large asteroid
    Given a large asteroid (radius 50) is approaching the player
    When the distance between player and asteroid centers < 50 + player_radius
    Then the player's health should decrease by 2
    And a screen shake effect should trigger (5px amplitude, 200ms)
    And 10 explosion particles should spawn at collision point
    And the player should enter invulnerability state for 1 second
    And the spacecraft should flash red during invulnerability

  @collision @damage
  Scenario: Player collides with medium asteroid
    Given a medium asteroid (radius 25) is approaching the player
    When collision is detected
    Then the player's health should decrease by 1
    And screen shake and particles should trigger

  @collision @damage
  Scenario: Player collides with small asteroid
    Given a small asteroid (radius 12) is approaching the player
    When collision is detected
    Then the player's health should decrease by 0.5
    And visual feedback should be proportionally smaller

  @collision @invulnerability
  Scenario: Player is invulnerable immediately after hit
    Given the player just collided with an asteroid
    And invulnerability timer is active
    When another asteroid touches the player within 1 second
    Then no additional health should be deducted
    And the spacecraft should continue flashing red

  @collision @game-over
  Scenario: Player health reaches zero
    Given the player has 1 health remaining
    When the player collides with a large asteroid (2 damage)
    Then the player's health should be clamped at 0
    And the game state should change to "gameover"
    And the high score table should be displayed
    And a "RESTART" button should appear

---

@epic-2-progression
Feature: Level Advancement and Difficulty Scaling
  As a player
  I want increasing difficulty as I progress
  So that the game remains challenging and engaging

  Background:
    Given the game is in "playing" state

  @progression @level-up
  Scenario: Player completes a wave and levels up
    Given the current level is 1
    And 3 large asteroids have spawned
    When all asteroids (including splits) are destroyed
    Then the level should increase to 2
    And a voice line "Well done, Cap!" should play
    And the game should pause for 2 seconds
    And the speed multiplier should update to 1 + (2 * 0.1) = 1.2

  @progression @asteroid-count
  Scenario: Asteroid count increases with level
    Given the player has just advanced to level 5
    When the new wave spawns
    Then the number of large asteroids should be 3 + 5 = 8
    And each asteroid should spawn with safe distance from player

  @progression @speed-scaling
  Scenario: Game speed increases with level
    Given the player is at level 3
    When any entity's velocity is calculated
    Then the velocity should be multiplied by 1 + (3 * 0.1) = 1.3
    And this should affect asteroids, bullets, and particles

  @progression @rotation-scaling
  Scenario: Asteroid rotation scales with level
    Given the player is at level 4
    When a large asteroid spawns
    Then its rotation speed should be base_rotation * 1.4
    And the rotation should accumulate each frame

---

@epic-2-progression
Feature: Score System
  As a player
  I want my score to reflect my performance
  So that I have a measurable goal

  Background:
    Given the game is in "playing" state
    And the player's score is 0

  @score @points
  Scenario: Destroying a large asteroid awards points
    Given a large asteroid exists
    When the player destroys it with a bullet
    Then the score should increase by 20 points
    And the HUD score display should update immediately

  @score @points
  Scenario: Destroying a medium asteroid awards more points
    Given a medium asteroid exists
    When the player destroys it with a bullet
    Then the score should increase by 50 points

  @score @points
  Scenario: Destroying a small asteroid awards maximum points
    Given a small asteroid exists
    When the player destroys it with a bullet
    Then the score should increase by 100 points

  @score @combo
  Scenario: Consecutive kills within 2 seconds grant multiplier
    Given the player destroyed an asteroid 1 second ago
    When the player destroys another asteroid now
    Then the points should be multiplied by 1.5x
    And a visual "COMBO!" indicator should flash

  @score @high-score
  Scenario: High score persists in localStorage
    Given the player's final score is 5000
    And the previous high score was 3000
    When the game ends
    Then the high score should update to 5000 in localStorage
    And the high score table should display the new score

---

@epic-3-audio
Feature: Synthesized Sound Effects
  As a player
  I want satisfying audio feedback
  So that my actions feel impactful

  Background:
    Given the game audio is not muted
    And the AudioContext is initialized

  @audio @sfx
  Scenario: Shooting produces synthesized sound
    When the player fires a bullet
    Then a 200Hz oscillator sound should play
    And the sound should have a 50ms exponential decay
    And the sound should use Web Audio API OscillatorNode

  @audio @sfx
  Scenario: Explosion produces noise-based sound
    When an asteroid is destroyed
    Then a white noise sound should play
    And the sound should use an exponential gain envelope
    And the duration should be 300ms

  @audio @sfx
  Scenario: Level-up produces melodic chime
    When the player completes a wave
    Then an ascending chord (C-E-G) should play
    And each note should be a separate oscillator
    And the chord should last 500ms

  @audio @mute
  Scenario: Mute toggle disables all SFX
    Given audio is currently playing
    When the player clicks the mute button
    Then all Web Audio oscillators should stop
    And the mute state should persist in localStorage
    And the mute button icon should show strikethrough

---

@epic-3-audio
Feature: Voice Encouragement System
  As a player
  I want enthusiastic voice lines
  So that the game feels more rewarding

  Background:
    Given the game audio is not muted
    And Web Speech Synthesis API is available

  @audio @voice
  Scenario: Voice line on asteroid destruction
    When the player destroys any asteroid
    And speechSynthesis is not currently speaking
    Then the phrase "Oh, yes!" should be queued
    And the system voice should speak it
    And no other voice lines should overlap

  @audio @voice
  Scenario: Voice line on level-up
    When the player completes a wave
    Then the phrase "Well done, Cap!" should be queued
    And it should interrupt any pending "Oh, yes!" lines

  @audio @voice
  Scenario: Voice line on weapon pickup
    When the player collects a weapon powerup
    Then the phrase "Excellent!" should be queued

  @audio @voice @mute
  Scenario: Mute toggle disables voice lines
    Given the mute button is active
    When any voice-triggering event occurs
    Then speechSynthesis.speak() should not be called
    And the queue should remain empty

---

@epic-4-platform
Feature: Mobile Touch Controls
  As a mobile player
  I want touch-optimized controls
  So that gameplay is as smooth as desktop

  Background:
    Given the user agent indicates a mobile device
    And the game has initialized mobile mode

  @mobile @ui
  Scenario: Virtual joystick renders correctly
    When the game canvas loads
    Then a semi-transparent joystick should render at bottom-left
    And the outer circle should be 120px diameter
    And the inner knob should be 50px diameter
    And the color should be hsla(200, 100%, 50%, 0.3)

  @mobile @ui
  Scenario: Fire button renders correctly
    When the game canvas loads
    Then a fire button should render at bottom-right
    And the button should be 100px diameter
    And the label "FIRE" should be centered in monospace 16px
    And the default color should be hsla(0, 80%, 50%, 0.5)

  @mobile @input
  Scenario: Joystick responds to touch
    Given the joystick is rendered
    When the player touches within the outer circle at offset (30, -30)
    Then the inner knob should move to that offset
    And the spacecraft should receive directional input (right-up)
    And the movement should normalize to max speed 5 pixels/frame

  @mobile @input
  Scenario: Fire button responds to touch
    Given the fire button is rendered
    When the player performs touchstart on the button
    Then the button should change to solid red hsl(0, 80%, 50%)
    And bullets should fire continuously until touchend
    And the fire rate should match desktop (10 bullets/second)

  @mobile @viewport
  Scenario: Viewport prevents zooming
    When the game loads on mobile
    Then the <meta name="viewport"> should include "user-scalable=no"
    And pinch-to-zoom should be disabled
    And the canvas should fill the available screen

---

@epic-4-platform
Feature: Cross-Browser Compatibility
  As a player on any browser
  I expect consistent performance
  So that I can play without technical issues

  @compatibility @performance
  Scenario: Game runs at 60fps on Chrome 90+
    Given the browser is Chrome version 90 or higher
    When the game loop runs for 5 seconds
    Then the average frame time should be < 16.67ms
    And no frame should exceed 33ms (30fps minimum)

  @compatibility @performance
  Scenario: Game runs at 60fps on Firefox 88+
    Given the browser is Firefox version 88 or higher
    When the game loop runs for 5 seconds
    Then performance should match Chrome benchmarks

  @compatibility @performance
  Scenario: Game runs at 60fps on Safari 14+
    Given the browser is Safari version 14 or higher
    When the game loop runs for 5 seconds
    Then performance should match Chrome benchmarks

  @compatibility @fallback
  Scenario: Graceful degradation on unsupported browser
    Given the browser does not support Canvas API
    When the game attempts to initialize
    Then an error message should display: "Your browser does not support HTML5 Canvas. Please use Chrome 90+, Firefox 88+, or Safari 14+."
    And the game should not attempt to render

  @compatibility @deployment
  Scenario: Relative paths work on GitHub Pages
    Given the game is deployed to GitHub Pages at https://username.github.io/void-hunter-redux/
    When the browser loads index.html
    Then ./css/style.css should load successfully
    And ./js/main.js should load successfully
    And no 404 errors should occur in the network tab

---

@epic-5-visual-polish
Feature: Particle Explosion Effects
  As a player
  I want satisfying explosion visuals
  So that destroying asteroids feels rewarding

  Background:
    Given the game is in "playing" state

  @particles @explosion
  Scenario: Asteroid destruction spawns particles
    Given a medium asteroid is destroyed
    When the destruction event fires
    Then 20-30 particles should spawn at the asteroid's center
    And each particle should have a random velocity (2-5 pixels/frame)
    And particle colors should alternate between hsl(40, 100%, 60%) and hsl(20, 90%, 50%)
    And particles should be 2px circles

  @particles @animation
  Scenario: Particles fade out over time
    Given 25 particles have spawned from an explosion
    When 30 frames (0.5 seconds) have passed
    Then all particles should have alpha = 0
    And they should be removed from the game state
    And the fade should be linear (alpha -= 1/30 per frame)

  @particles @pooling
  Scenario: Particle object pooling prevents memory spikes
    Given 10 asteroids have been destroyed in quick succession
    When particles are spawned for each explosion
    Then the total number of active particle objects should not exceed 300
    And inactive particles should be reused instead of creating new objects
    And no garbage collection pauses should exceed 5ms

---

@epic-5-visual-polish
Feature: Parallax Starfield Background
  As a player
  I want an immersive background
  So that the game feels dynamic and polished

  Background:
    Given the game has initialized

  @background @starfield
  Scenario: Three layers of stars render on initialization
    When the game canvas loads
    Then layer 1 (far) should contain 50 stars at hsl(0, 0%, 40%)
    And layer 2 (mid) should contain 100 stars at hsl(0, 0%, 60%)
    And layer 3 (near) should contain 150 stars at hsl(0, 0%, 80%)
    And all stars should be 1-3 pixel circles at random positions

  @background @parallax
  Scenario: Stars scroll at different speeds
    Given the game speed multiplier is 1.0
    When 60 frames have passed
    Then layer 1 stars should have moved at 0.5x speed
    And layer 2 stars should have moved at 1.0x speed
    And layer 3 stars should have moved at 1.5x speed
    And the direction should be downward (simulating player movement up)

  @background @wrapping
  Scenario: Stars wrap around screen edges
    Given a star in layer 3 is at Y = canvas.height + 10
    When the next frame renders
    Then the star should reappear at Y = -10
    And the X position should remain unchanged
    And the wrapping should be seamless (no flicker)

  @background @layering
  Scenario: Stars render behind game entities
    Given the starfield is active
    When the canvas draws each frame
    Then stars should be drawn first (bottom z-index)
    And player, asteroids, bullets should draw after stars
    And particles should draw last (top z-index)

---

@epic-5-visual-polish
Feature: Screen Shake Effect
  As a player
  I want screen shake on large impacts
  So that collisions feel more impactful

  @screenshake @trigger
  Scenario: Large asteroid collision triggers screen shake
    Given the player collides with a large asteroid (radius 50)
    When the collision is detected
    Then the canvas offset should shake with 5px amplitude
    And the shake should last 200ms (12 frames at 60fps)
    And the offset should use random X and Y values within ±5px

  @screenshake @easing
  Scenario: Screen shake uses exponential decay
    Given screen shake has been triggered
    When each frame updates
    Then the shake amplitude should decay exponentially
    And the formula should be: current_amplitude = 5 * (0.9 ^ frame_count)
    And the shake should stop when amplitude < 0.5px

  @screenshake @no-overlap
  Scenario: New screen shake extends existing shake
    Given screen shake is currently active at frame 6 (halfway)
    When another large collision occurs
    Then the shake timer should reset to frame 0
    And the amplitude should reset to 5px
    And the previous shake should not create a "double shake" artifact

---

# Validation Checklist
# - [x] All user stories from PRD converted to Gherkin scenarios
# - [x] Each scenario uses Given-When-Then structure
# - [x] Acceptance criteria are testable with specific values
# - [x] Background contexts reduce repetition
# - [x] Tags enable selective test execution
# - [x] Edge cases included (e.g., invulnerability, mute states)

# Technical Completeness Review
# - [x] PRD contains sufficient implementation detail
# - [x] Data schemas are defined in /artifacts/02_pm_prd.md
# - [x] Color values use HSL format as required
# - [x] Performance benchmarks are measurable (60fps, <16.67ms frames)
# - [x] Mobile and desktop scenarios are separated with tags

# Validation Status: APPROVED
# Next Agent: Engineering Manager (Stage 4)
